STATUS_ZH = {
    "delivered": "已签收", "delivering": "运输中", "cancelled": "已取消",
    "awaiting_deliver": "等待发运", "awaiting_packaging": "待备货",
    "awaiting_registration": "等待登记",
}
PUSH_EVENT_TYPES = (
    "TYPE_NEW_POSTING", "TYPE_POSTING_CANCELLED", "TYPE_STATE_CHANGED",
    "TYPE_FBO_POSTING_NEW", "TYPE_FBO_POSTING_CANCELLED", "TYPE_FBO_POSTING_STATE_CHANGED",
    "TYPE_STOCKS_CHANGED", "TYPE_FBO_STOCKS_CHANGED",
    "TYPE_ORDER_NEW", "TYPE_ORDER_CANCELLED", "TYPE_ORDER_STATE_CHANGED",
)
PUSH_POSTING_TYPES = {
    "TYPE_NEW_POSTING", "TYPE_POSTING_CANCELLED", "TYPE_STATE_CHANGED",
    "TYPE_FBO_POSTING_NEW", "TYPE_FBO_POSTING_CANCELLED", "TYPE_FBO_POSTING_STATE_CHANGED",
}
PUSH_CANCEL_TYPES = {"TYPE_POSTING_CANCELLED", "TYPE_FBO_POSTING_CANCELLED"}
PUSH_STATE_TYPES = {"TYPE_STATE_CHANGED", "TYPE_FBO_POSTING_STATE_CHANGED"}
PUSH_STOCK_TYPES = {"TYPE_STOCKS_CHANGED", "TYPE_FBO_STOCKS_CHANGED"}
PUSH_ORDER_TYPES = {"TYPE_ORDER_NEW", "TYPE_ORDER_CANCELLED", "TYPE_ORDER_STATE_CHANGED"}
PUSH_STATUS_ZH = {
    "posting_created": "待备货",
    "posting_acceptance_in_progress": "待备货",
    "posting_awaiting_registration": "等待登记",
    "posting_transferring_to_delivery": "等待发运",
    "posting_in_carriage": "运输中",
    "posting_on_way_to_city": "运输中",
    "posting_on_way_to_pickup_point": "运输中",
    "posting_transferred_to_courier_service": "运输中",
    "posting_in_courier_service": "运输中",
    "posting_in_pickup_point": "运输中",
    "posting_conditionally_delivered": "运输中",
    "posting_driver_pick_up": "运输中",
    "posting_delivered": "已签收",
    "posting_received": "已签收",
    "posting_canceled": "已取消",
    "posting_cancelled": "已取消",
    "canceled": "已取消",
    "cancelled": "已取消",
}
RETURN_STATUS_ZH = {
    "На складе": "在仓库中",
    "Едет на склад": "正在运往仓库",
    "Списали товар": "我们已核销商品",
    "Ожидает отправки": "等待发货",
}
RFBS_RETURN_STATUS_ZH = {
    "Rejected": "由您拒绝",
    "PartialCompensationReturnedByOzon": "已向买家赔偿",
    "Cancelled": "由买家取消",
    "ReleasedByProvider": "已由合作伙伴发送",
    "RejectedByOzon": "由Ozon拒绝了",
    "CancelledDisputeNotOpen": "已拒绝。未提出争议",
    "CancelledDisputeNotOpenOnPostModeration": "已拒绝。未提出争议",
    "UtilizedByOzon": "已由Ozon销毁",
    "ArrivedAtWarehouse": "在仓库中",
    "PartialCompensationReturned": "您已退还部分金额",
    "MoneyReturned": "已退款",
    "AwaitingProcessing": "等待决定",
    "OnSellerApproval": "待卖家审核",
    "OnSellerClarification": "确认中",
    "OnWayToOzon": "在途中",
    "UtilizedByProvider": "已由合作伙伴销毁",
    "ApprovedOnPreModerationByOzon": "已由Ozon批准",
    "CheckingStatus": "正在确认状态",
    "PassedToPartner": "已转交给合作伙伴",
    "Approved": "由您认可",
    "OnWay": "在途中",
    "UtilizingByOzon": "正在由Ozon进行销毁",
    "CrmRejected": "由Ozon拒绝了",
    "OnSellerClarificationAfterPartialCompensation": "确认中",
    "Solved": "已说明",
    "WriteOff": "我们已核销商品",
    "ReceivedBySeller": "已收货",
}
CANCEL_REASON_ZH = {
    "Покупатель отказался при вручении: товар не подошел": "买家在交货时拒收：商品不合适",
    "Отправление не прошло таможенное оформление": "货件未通过清关",
    "Не удалось доставить заказ": "未能配送订单",
    "Покупатель не забрал заказ": "买家没取货",
    "Покупатель отменил заказ: нашел дешевле": "买家取消了订单：找到了更便宜的商品",
    "Покупатель отменил заказ": "买家取消了订单",
    "Заказ утерян при доставке": "订单在配送过程中丢失",
    "Покупатель не предоставил паспортные данные": "买家没提供护照信息",
    "Товар закончился на складе": "仓库缺货",
    "Покупатель отменил заказ: не устроил срок доставки": "买方取消订单：对交货时间不满意",
    "Покупатель отказался при вручении: в заказе не тот товар": "买家在交货时拒收：订单中的商品有误",
    "Покупатель отказался при вручении: недоволен качеством товара": "买家拒绝取货：对商品质量不满意",
    "Вы отменили заказ": "您已取消订单",
    "Покупатель отменил заказ: перенос сроков доставки": "买家取消了订单： 推迟配送期间",
    "Покупатель отменил заказ по вашей просьбе": "买家应您的要求取消了订单",
    "Покупатель отказался при вручении: неполная комплектация": "买家在交货时拒收：商品不齐全",
    "Товар не работает / брак": "商品无法使用 / 存在缺陷",
    "Покупатель получил не те товары": "买家收到错误的商品",
    "Покупатель передумал": "买家改变主意",
    "Упаковка и товар повреждены": "包装和商品均损坏",
    "Товар в неполной комплектации": "商品不齐全",
    "Товар поврежден, но упаковка цела": "商品损坏，但包装完好无损",
    "Товар или заводскую упаковку повредили": "商品或原厂包装已损坏",
    "Товар использовали до меня": "我收到前商品已被使用",
    "Есть внешние дефекты или следы использования": "有外部缺陷或使用痕迹",
    "Привезли не тот товар": "配送了错误的商品",
    "Нет части товара или комплекта": "商品或套装部件缺失",
    "Нет части товара/комплекта": "商品/套件缺失部分",
    "Не работает, плохо работает": "无法使用，使用效果差",
    "Подделка": "假货",
    "Товар сломался при использовании": "商品在使用过程中坏了",
    "Не подошёл товар": "商品不合适",
    "Товар не подошёл": "商品不合适",
    "Не работает или работает плохо": "不可用或无法正常工作",
    "Покупатель попросил вас отменить заказ": "买家已要求您取消订单",
    "Вы не отгрузили заказ вовремя": "您没有按时发送商品",
    "Не соответствует требованиям перевозчика": "不符合承运商的要求",
    "Не удалось зарегистрировать отправление в службе доставки": "未能通过送货服务登记货件",
    "Вы нарушили правила перевозки опасных товаров": "您违反了危险品运输规则",
    "Трек-номер не отслеживается": "追踪号码无法追踪",
    "Покупатель не оплатил пошлину": "买家未缴纳关税",
    "Покупатель не оплатил заказ вовремя": "买方未按时支付订单",
    "Не удалось обработать заказ": "未能处理订单",
    "У товаров неправильная этикетка": "商品标签错误",
    "Проверка товара на соответствие описанию в карточке": "检查商品是否与商品卡片中的描述相符",
    "Отменили заказ по вашей просьбе": "已根据您的要求取消订单",
    "В заказе есть запрещённые к перевозке товары": "订单中有禁止运输的商品",
}
